---
deployment:
  tasks:
    - export DEPLOYMENT_SOURCE=$PWD
    - export DEPLOYMENT_TARGET=/home/anae4363/public_html
    - echo "Deploying from $DEPLOYMENT_SOURCE to $DEPLOYMENT_TARGET"
    - /bin/ls -la $DEPLOYMENT_SOURCE/build
    - /bin/ls -la $DEPLOYMENT_TARGET
    - /bin/cp -r $DEPLOYMENT_SOURCE/build/* $DEPLOYMENT_TARGET
    - /bin/ls -la $DEPLOYMENT_TARGET
