name: Deploy to cPanel

on:
  push:
    branches:
      - main # Ganti dengan nama branch yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Versi Node.js yang sesuai

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to cPanel
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASS: ${{ secrets.CPANEL_PASS }}
          CPANEL_DOMAIN: ${{ secrets.CPANEL_DOMAIN }}
        run: |
          curl -u $CPANEL_USER:$CPANEL_PASS \
               --ftp-create-dirs \
               -T build/* \
               ftp://$CPANEL_DOMAIN/public_html/
